// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package dto

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BillCreation defines model for BillCreation.
type BillCreation struct {
	Amount      float32            `json:"amount"`
	Description *string            `json:"description,omitempty"`
	DueDate     openapi_types.Date `json:"dueDate"`
}

// BillUpdate defines model for BillUpdate.
type BillUpdate struct {
	Amount      *float32            `json:"amount,omitempty"`
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"dueDate,omitempty"`
}

// FeedbackRating defines model for FeedbackRating.
type FeedbackRating struct {
	// Comment Additional comments or feedback from the user
	Comment *string `json:"comment,omitempty"`

	// MerchantId The ID of the merchant being rated
	MerchantId string `json:"merchantId"`

	// Rating The numerical rating given by the user (e.g., 1-5)
	Rating float32 `json:"rating"`
}

// GoalCreation defines model for GoalCreation.
type GoalCreation struct {
	// Amount The target amount for the financial goal
	Amount float32 `json:"amount"`

	// Name The name or description of the financial goal
	Name string `json:"name"`
}

// GoalUpdate defines model for GoalUpdate.
type GoalUpdate struct {
	// Amount The updated target amount for the financial goal
	Amount *float32 `json:"amount,omitempty"`

	// Name The updated name or description of the financial goal
	Name *string `json:"name,omitempty"`
}

// IntegrationConnect defines model for IntegrationConnect.
type IntegrationConnect struct {
	ApiKey      string                  `json:"apiKey"`
	Credentials *map[string]interface{} `json:"credentials,omitempty"`
	Platform    string                  `json:"platform"`
}

// NotificationSend defines model for NotificationSend.
type NotificationSend struct {
	Date      time.Time           `json:"date"`
	Message   string              `json:"message"`
	Recipient openapi_types.Email `json:"recipient"`
}

// PasswordReset defines model for PasswordReset.
type PasswordReset struct {
	Password string `json:"password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ReportGeneration defines model for ReportGeneration.
type ReportGeneration struct {
	EndDate   openapi_types.Date `json:"endDate"`
	StartDate openapi_types.Date `json:"startDate"`
	Type      string             `json:"type"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// UserProfileUpdate defines model for UserProfileUpdate.
type UserProfileUpdate struct {
	Email    openapi_types.Email `json:"email"`
	Username string              `json:"username"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// PostApiAuthLoginJSONRequestBody defines body for PostApiAuthLogin for application/json ContentType.
type PostApiAuthLoginJSONRequestBody = UserLogin

// PutApiAuthProfileJSONRequestBody defines body for PutApiAuthProfile for application/json ContentType.
type PutApiAuthProfileJSONRequestBody = UserProfileUpdate

// PostApiAuthRegisterJSONRequestBody defines body for PostApiAuthRegister for application/json ContentType.
type PostApiAuthRegisterJSONRequestBody = UserRegistration

// PostApiAuthResetJSONRequestBody defines body for PostApiAuthReset for application/json ContentType.
type PostApiAuthResetJSONRequestBody = PasswordResetRequest

// PutApiAuthResetTokenJSONRequestBody defines body for PutApiAuthResetToken for application/json ContentType.
type PutApiAuthResetTokenJSONRequestBody = PasswordReset

// PostApiBillsJSONRequestBody defines body for PostApiBills for application/json ContentType.
type PostApiBillsJSONRequestBody = BillCreation

// PutApiBillsIdJSONRequestBody defines body for PutApiBillsId for application/json ContentType.
type PutApiBillsIdJSONRequestBody = BillUpdate

// PostApiFeedbackJSONRequestBody defines body for PostApiFeedback for application/json ContentType.
type PostApiFeedbackJSONRequestBody = FeedbackRating

// PostApiGoalsJSONRequestBody defines body for PostApiGoals for application/json ContentType.
type PostApiGoalsJSONRequestBody = GoalCreation

// PutApiGoalsIdJSONRequestBody defines body for PutApiGoalsId for application/json ContentType.
type PutApiGoalsIdJSONRequestBody = GoalUpdate

// PostApiIntegrationsJSONRequestBody defines body for PostApiIntegrations for application/json ContentType.
type PostApiIntegrationsJSONRequestBody = IntegrationConnect

// PostApiNotificationsJSONRequestBody defines body for PostApiNotifications for application/json ContentType.
type PostApiNotificationsJSONRequestBody = NotificationSend

// PostApiReportsJSONRequestBody defines body for PostApiReports for application/json ContentType.
type PostApiReportsJSONRequestBody = ReportGeneration
